$(document).ready(function() {
  $('.burger').click(function () {
    $('.burgerlist').toggleClass('active')
  })
  $('.cafe').click(function () {
    $('.cafe').toggleClass('active')
    $('.hospital').removeClass('active')
    $('.restaurant').removeClass('active')
    $('.pharmacy').removeClass('active')
    $('.store').removeClass('active')
    $('.supermarket').removeClass('active')
    $('.parking').removeClass('active')
    $('.doctor').removeClass('active')
  })
  $('.hospital').click(function () {
    $('.hospital').toggleClass('active')
    $('.cafe').removeClass('active')
    $('.restaurant').removeClass('active')
    $('.pharmacy').removeClass('active')
    $('.store').removeClass('active')
    $('.supermarket').removeClass('active')
    $('.parking').removeClass('active')
    $('.doctor').removeClass('active')
  })
  $('.restaurant').click(function () {
    $('.restaurant').toggleClass('active')
    $('.hospital').removeClass('active')
    $('.cafe').removeClass('active')
    $('.pharmacy').removeClass('active')
    $('.store').removeClass('active')
    $('.supermarket').removeClass('active')
    $('.parking').removeClass('active')
    $('.doctor').removeClass('active')
  })
  $('.pharmacy').click(function () {
    $('.pharmacy').toggleClass('active')
    $('.hospital').removeClass('active')
    $('.restaurant').removeClass('active')
    $('.cafe').removeClass('active')
    $('.store').removeClass('active')
    $('.supermarket').removeClass('active')
    $('.parking').removeClass('active')
    $('.doctor').removeClass('active')
  })
  $('.store').click(function () {
    $('.store').toggleClass('active')
    $('.hospital').removeClass('active')
    $('.restaurant').removeClass('active')
    $('.pharmacy').removeClass('active')
    $('.cafe').removeClass('active')
    $('.supermarket').removeClass('active')
    $('.parking').removeClass('active')
    $('.doctor').removeClass('active')
  })
  $('.supermarket').click(function () {
    $('.supermarket').toggleClass('active')
    $('.hospital').removeClass('active')
    $('.restaurant').removeClass('active')
    $('.pharmacy').removeClass('active')
    $('.store').removeClass('active')
    $('.cafe').removeClass('active')
    $('.parking').removeClass('active')
    $('.doctor').removeClass('active')
  })
  $('.parking').click(function () {
    $('.parking').toggleClass('active')
    $('.hospital').removeClass('active')
    $('.restaurant').removeClass('active')
    $('.pharmacy').removeClass('active')
    $('.store').removeClass('active')
    $('.supermarket').removeClass('active')
    $('.cafe').removeClass('active')
    $('.doctor').removeClass('active')
  })
  $('.doctor').click(function () {
    $('.doctor').toggleClass('active')
    $('.hospital').removeClass('active')
    $('.restaurant').removeClass('active')
    $('.pharmacy').removeClass('active')
    $('.store').removeClass('active')
    $('.supermarket').removeClass('active')
    $('.parking').removeClass('active')
    $('.cafe').removeClass('active')
  })
});

