$(document).ready(function() {
  $('.burger').click(function () {
    $('.burgerlist').toggleClass('active')
  })
  $('.store1').click(function () {
    $('.store1').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store2').click(function () {
    $('.store2').toggleClass('active')
    $('.store1').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store3').click(function () {
    $('.store3').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store1').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store4').click(function () {
    $('.store4').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store1').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store5').click(function () {
    $('.store5').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store1').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store6').click(function () {
    $('.store6').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store1').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store7').click(function () {
    $('.store7').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store1').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store8').click(function () {
    $('.store8').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store1').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store9').click(function () {
    $('.store9').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store1').removeClass('active')
    $('.store10').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store10').click(function () {
    $('.store10').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store1').removeClass('active')
    $('.store11').removeClass('active')
  })
  $('.store11').click(function () {
    $('.store11').toggleClass('active')
    $('.store2').removeClass('active')
    $('.store3').removeClass('active')
    $('.store4').removeClass('active')
    $('.store5').removeClass('active')
    $('.store6').removeClass('active')
    $('.store7').removeClass('active')
    $('.store8').removeClass('active')
    $('.store9').removeClass('active')
    $('.store10').removeClass('active')
    $('.store1').removeClass('active')
  })
  $('.pay1').click(function () {
    $('.pay1').toggleClass('active')
  })
  $('.pay2').click(function () {
    $('.pay2').toggleClass('active')
  })
  $('.pay3').click(function () {
    $('.pay3').toggleClass('active')
  })
  $('.pay4').click(function () {
    $('.pay4').toggleClass('active')
  })
  $('.pay5').click(function () {
    $('.pay5').toggleClass('active')
  })
  $('.pay6').click(function () {
    $('.pay6').toggleClass('active')
  })
  $('.pay7').click(function () {
    $('.pay7').toggleClass('active')
  })
  $('.pay8').click(function () {
    $('.pay8').toggleClass('active')
  })
  $('.pay9').click(function () {
    $('.pay9').toggleClass('active')
  })
  $('.pay10').click(function () {
    $('.pay10').toggleClass('active')
  })
  $('.pay11').click(function () {
    $('.pay11').toggleClass('active')
  })
  $('.pay12').click(function () {
    $('.pay12').toggleClass('active')
  })
});

