$('#prev1').on('click', function() {
  $('storeUl').animate({
    scrollLeft: '-=100'
  }, 300, 'swing');
});
$('#next1').on('click', function() {
  $('storeUl').animate({
    scrollLeft: '+=100'
  }, 300, 'swing');
});
$('#prev2').on('click', function() {
  $('payUl').animate({
    scrollLeft: '-=100'
  }, 300, 'swing');
});
$('#next2').on('click', function() {
  $('payUl').animate({
    scrollLeft: '+=100'
  }, 300, 'swing');
});

//input range
// let i = document.getElementsByClassName('.laBar'),
//     o = document.getElementsByClassName('.laBarOutput');
// o.innerHTML = i.value;

// // use 'change' instead to see the difference in response
// $('.laBar').addEventListener('.laBar', function () {
//   o.innerHTML = i.value;
// }, false);
// function value(value) {
//   var obj1 = document.getElementByClassName("laBarOutput");
//   obj1.innerHTML = value;
// }
// function showVal(laBarOutput){
//   document.getElementByClassName("valBox").innerHTML=newVal;
// }

function getValue(){
  var range=document.getElementById('range');
  var value=range.value;
  console.log(value);
}

//CreditFeedback
  var c = '.creditCard';
  var f = '.feedback';
  $(document).ready(function() {
    $(c+1).hover(function () {$(f+1).toggleClass('active')})
    $(c+2).hover(function () {$(f+2).toggleClass('active')})
    $(c+3).hover(function () {$(f+3).toggleClass('active')})
    $(c+4).hover(function () {$(f+4).toggleClass('active')})
    $(c+5).hover(function () {$(f+5).toggleClass('active')})
    $(c+6).hover(function () {$(f+6).toggleClass('active')})
    $(c+7).hover(function () {$(f+7).toggleClass('active')})
    $(c+8).hover(function () {$(f+8).toggleClass('active')})
    $(c+9).hover(function () {$(f+9).toggleClass('active')})
    $(c+10).hover(function () {$(f+10).toggleClass('active')})
    $(c+11).hover(function () {$(f+11).toggleClass('active')})
    $(c+12).hover(function () {$(f+12).toggleClass('active')})
    $(c+13).hover(function () {$(f+13).toggleClass('active')})
    $(c+14).hover(function () {$(f+14).toggleClass('active')})
    $(c+15).hover(function () {$(f+15).toggleClass('active')})
    $(c+16).hover(function () {$(f+16).toggleClass('active')})
    $(c+17).hover(function () {$(f+17).toggleClass('active')})
    $(c+18).hover(function () {$(f+18).toggleClass('active')})
    $(c+19).hover(function () {$(f+19).toggleClass('active')})
    $(c+20).hover(function () {$(f+20).toggleClass('active')})
    $(c+21).hover(function () {$(f+21).toggleClass('active')})
    $(c+22).hover(function () {$(f+22).toggleClass('active')})
    $(c+23).hover(function () {$(f+23).toggleClass('active')})
    $(c+24).hover(function () {$(f+24).toggleClass('active')})
    $(c+25).hover(function () {$(f+25).toggleClass('active')})
    $(c+26).hover(function () {$(f+26).toggleClass('active')})
    $(c+27).hover(function () {$(f+27).toggleClass('active')})
    $(c+28).hover(function () {$(f+28).toggleClass('active')})
    $(c+29).hover(function () {$(f+29).toggleClass('active')})
    $(c+30).hover(function () {$(f+30).toggleClass('active')})
    $(c+31).hover(function () {$(f+31).toggleClass('active')})
    $(c+32).hover(function () {$(f+32).toggleClass('active')})
    $(c+33).hover(function () {$(f+33).toggleClass('active')})
    $(c+34).hover(function () {$(f+34).toggleClass('active')})
    $(c+35).hover(function () {$(f+35).toggleClass('active')})
    $(c+36).hover(function () {$(f+36).toggleClass('active')})
    $(c+37).hover(function () {$(f+37).toggleClass('active')})
    $(c+38).hover(function () {$(f+38).toggleClass('active')})
    $(c+39).hover(function () {$(f+39).toggleClass('active')})
    $(c+40).hover(function () {$(f+40).toggleClass('active')})
    $(c+41).hover(function () {$(f+41).toggleClass('active')})
    $(c+42).hover(function () {$(f+42).toggleClass('active')})
    $(c+43).hover(function () {$(f+43).toggleClass('active')})
    $(c+44).hover(function () {$(f+44).toggleClass('active')})
    $(c+45).hover(function () {$(f+45).toggleClass('active')})
    $(c+46).hover(function () {$(f+46).toggleClass('active')})
    $(c+47).hover(function () {$(f+47).toggleClass('active')})
    $(c+48).hover(function () {$(f+48).toggleClass('active')})
    $(c+49).hover(function () {$(f+49).toggleClass('active')})
    $(c+50).hover(function () {$(f+50).toggleClass('active')})
    $(c+51).hover(function () {$(f+51).toggleClass('active')})
    $(c+52).hover(function () {$(f+52).toggleClass('active')})
    $(c+53).hover(function () {$(f+53).toggleClass('active')})
    $(c+54).hover(function () {$(f+54).toggleClass('active')})
    $(c+55).hover(function () {$(f+55).toggleClass('active')})
    $(c+56).hover(function () {$(f+56).toggleClass('active')})
    $(c+57).hover(function () {$(f+57).toggleClass('active')})
    $(c+58).hover(function () {$(f+58).toggleClass('active')})
    $(c+59).hover(function () {$(f+59).toggleClass('active')})
    $(c+60).hover(function () {$(f+60).toggleClass('active')})
    $(c+61).hover(function () {$(f+61).toggleClass('active')})
    $(c+62).hover(function () {$(f+62).toggleClass('active')})
    $(c+63).hover(function () {$(f+63).toggleClass('active')})
    $(c+64).hover(function () {$(f+64).toggleClass('active')})
    $(c+65).hover(function () {$(f+65).toggleClass('active')})
    $(c+66).hover(function () {$(f+66).toggleClass('active')})
    $(c+67).hover(function () {$(f+67).toggleClass('active')})
    $(c+68).hover(function () {$(f+68).toggleClass('active')})
    $(c+69).hover(function () {$(f+69).toggleClass('active')})
    $(c+70).hover(function () {$(f+70).toggleClass('active')})
    $(c+71).hover(function () {$(f+71).toggleClass('active')})
    $(c+72).hover(function () {$(f+72).toggleClass('active')})
    $(c+73).hover(function () {$(f+73).toggleClass('active')})
    $(c+74).hover(function () {$(f+74).toggleClass('active')})
    $(c+75).hover(function () {$(f+75).toggleClass('active')})
    $(c+76).hover(function () {$(f+76).toggleClass('active')})
    $(c+77).hover(function () {$(f+77).toggleClass('active')})
    $(c+78).hover(function () {$(f+78).toggleClass('active')})
    $(c+79).hover(function () {$(f+79).toggleClass('active')})
    $(c+80).hover(function () {$(f+80).toggleClass('active')})
    $(c+81).hover(function () {$(f+81).toggleClass('active')})
    $(c+82).hover(function () {$(f+82).toggleClass('active')})
    $(c+83).hover(function () {$(f+83).toggleClass('active')})
    $(c+84).hover(function () {$(f+84).toggleClass('active')})
    $(c+85).hover(function () {$(f+85).toggleClass('active')})
    $(c+86).hover(function () {$(f+86).toggleClass('active')})
    $(c+87).hover(function () {$(f+87).toggleClass('active')})
    $(c+88).hover(function () {$(f+88).toggleClass('active')})
    $(c+89).hover(function () {$(f+89).toggleClass('active')})
    $(c+90).hover(function () {$(f+90).toggleClass('active')})
    $(c+91).hover(function () {$(f+91).toggleClass('active')})
    $(c+92).hover(function () {$(f+92).toggleClass('active')})
    $(c+93).hover(function () {$(f+93).toggleClass('active')})
    $(c+94).hover(function () {$(f+94).toggleClass('active')})
    $(c+95).hover(function () {$(f+95).toggleClass('active')})
    $(c+96).hover(function () {$(f+96).toggleClass('active')})
    $(c+97).hover(function () {$(f+97).toggleClass('active')})
    $(c+98).hover(function () {$(f+98).toggleClass('active')})
    $(c+99).hover(function () {$(f+99).toggleClass('active')})
    $(c+100).hover(function () {$(f+100).toggleClass('active')})
    $(c+101).hover(function () {$(f+101).toggleClass('active')})
    $(c+102).hover(function () {$(f+102).toggleClass('active')})
    $(c+103).hover(function () {$(f+103).toggleClass('active')})
    $(c+104).hover(function () {$(f+104).toggleClass('active')})
    $(c+105).hover(function () {$(f+105).toggleClass('active')})
    $(c+106).hover(function () {$(f+106).toggleClass('active')})
    $(c+107).hover(function () {$(f+107).toggleClass('active')})
    $(c+108).hover(function () {$(f+108).toggleClass('active')})
    $(c+109).hover(function () {$(f+109).toggleClass('active')})
    $(c+110).hover(function () {$(f+110).toggleClass('active')})
    $(c+111).hover(function () {$(f+111).toggleClass('active')})
    $(c+112).hover(function () {$(f+112).toggleClass('active')})
    $(c+113).hover(function () {$(f+113).toggleClass('active')})
    $(c+114).hover(function () {$(f+114).toggleClass('active')})
    $(c+115).hover(function () {$(f+115).toggleClass('active')})
    $(c+116).hover(function () {$(f+116).toggleClass('active')})
    $(c+117).hover(function () {$(f+117).toggleClass('active')})
    $(c+118).hover(function () {$(f+118).toggleClass('active')})
    $(c+119).hover(function () {$(f+119).toggleClass('active')})
    $(c+120).hover(function () {$(f+120).toggleClass('active')})
    $(c+121).hover(function () {$(f+121).toggleClass('active')})
    $(c+122).hover(function () {$(f+122).toggleClass('active')})
    $(c+123).hover(function () {$(f+123).toggleClass('active')})
    $(c+124).hover(function () {$(f+124).toggleClass('active')})
    $(c+125).hover(function () {$(f+125).toggleClass('active')})
    $(c+126).hover(function () {$(f+126).toggleClass('active')})
    $(c+127).hover(function () {$(f+127).toggleClass('active')})
    $(c+128).hover(function () {$(f+128).toggleClass('active')})
    $(c+129).hover(function () {$(f+129).toggleClass('active')})
    $(c+130).hover(function () {$(f+130).toggleClass('active')})
    $(c+131).hover(function () {$(f+131).toggleClass('active')})
    $(c+132).hover(function () {$(f+132).toggleClass('active')})
    $(c+133).hover(function () {$(f+133).toggleClass('active')})
    $(c+134).hover(function () {$(f+134).toggleClass('active')})
    $(c+135).hover(function () {$(f+135).toggleClass('active')})
    $(c+136).hover(function () {$(f+136).toggleClass('active')})
    $(c+137).hover(function () {$(f+137).toggleClass('active')})
    $(c+138).hover(function () {$(f+138).toggleClass('active')})
    $(c+139).hover(function () {$(f+139).toggleClass('active')})
    $(c+140).hover(function () {$(f+140).toggleClass('active')})
    $(c+141).hover(function () {$(f+141).toggleClass('active')})
    $(c+142).hover(function () {$(f+142).toggleClass('active')})
    $(c+143).hover(function () {$(f+143).toggleClass('active')})
    $(c+144).hover(function () {$(f+144).toggleClass('active')})
    $(c+145).hover(function () {$(f+145).toggleClass('active')})
    $(c+146).hover(function () {$(f+146).toggleClass('active')})
    $(c+147).hover(function () {$(f+147).toggleClass('active')})
    $(c+148).hover(function () {$(f+148).toggleClass('active')})
    $(c+149).hover(function () {$(f+149).toggleClass('active')})
    $(c+150).hover(function () {$(f+150).toggleClass('active')})
    $(c+151).hover(function () {$(f+151).toggleClass('active')})
    $(c+152).hover(function () {$(f+152).toggleClass('active')})
    $(c+153).hover(function () {$(f+153).toggleClass('active')})
    $(c+154).hover(function () {$(f+154).toggleClass('active')})
    $(c+155).hover(function () {$(f+155).toggleClass('active')})
    $(c+156).hover(function () {$(f+156).toggleClass('active')})
    $(c+157).hover(function () {$(f+157).toggleClass('active')})
    $(c+158).hover(function () {$(f+158).toggleClass('active')})
    $(c+159).hover(function () {$(f+159).toggleClass('active')})
    $(c+160).hover(function () {$(f+160).toggleClass('active')})
    $(c+161).hover(function () {$(f+161).toggleClass('active')})
    $(c+162).hover(function () {$(f+162).toggleClass('active')})
    $(c+163).hover(function () {$(f+163).toggleClass('active')})
    $(c+164).hover(function () {$(f+164).toggleClass('active')})
    $(c+165).hover(function () {$(f+165).toggleClass('active')})
    $(c+166).hover(function () {$(f+166).toggleClass('active')})
    $(c+167).hover(function () {$(f+167).toggleClass('active')})
    $(c+168).hover(function () {$(f+168).toggleClass('active')})
    $(c+169).hover(function () {$(f+169).toggleClass('active')})
    $(c+170).hover(function () {$(f+170).toggleClass('active')})
    $(c+171).hover(function () {$(f+171).toggleClass('active')})
    $(c+172).hover(function () {$(f+172).toggleClass('active')})
    $(c+173).hover(function () {$(f+173).toggleClass('active')})
    $(c+174).hover(function () {$(f+174).toggleClass('active')})
    $(c+175).hover(function () {$(f+175).toggleClass('active')})
    $(c+176).hover(function () {$(f+176).toggleClass('active')})
    $(c+177).hover(function () {$(f+177).toggleClass('active')})
    $(c+178).hover(function () {$(f+178).toggleClass('active')})
    $(c+179).hover(function () {$(f+179).toggleClass('active')})
    $(c+180).hover(function () {$(f+180).toggleClass('active')})
    $(c+181).hover(function () {$(f+181).toggleClass('active')})
    $(c+182).hover(function () {$(f+182).toggleClass('active')})
    $(c+183).hover(function () {$(f+183).toggleClass('active')})
    $(c+184).hover(function () {$(f+184).toggleClass('active')})
    $(c+185).hover(function () {$(f+185).toggleClass('active')})
    $(c+186).hover(function () {$(f+186).toggleClass('active')})
    $(c+187).hover(function () {$(f+187).toggleClass('active')})
    $(c+188).hover(function () {$(f+188).toggleClass('active')})
    $(c+189).hover(function () {$(f+189).toggleClass('active')})
    $(c+190).hover(function () {$(f+190).toggleClass('active')})
    $(c+191).hover(function () {$(f+191).toggleClass('active')})
    $(c+192).hover(function () {$(f+192).toggleClass('active')})
    $(c+193).hover(function () {$(f+193).toggleClass('active')})
    $(c+194).hover(function () {$(f+194).toggleClass('active')})
    $(c+195).hover(function () {$(f+195).toggleClass('active')})
    $(c+196).hover(function () {$(f+196).toggleClass('active')})
    $(c+197).hover(function () {$(f+197).toggleClass('active')})
    $(c+198).hover(function () {$(f+198).toggleClass('active')})
    $(c+199).hover(function () {$(f+199).toggleClass('active')})
    $(c+200).hover(function () {$(f+200).toggleClass('active')})
    $(c+201).hover(function () {$(f+201).toggleClass('active')})
    $(c+202).hover(function () {$(f+202).toggleClass('active')})
  });